#DEFINE CRLF  CHR(13)+CHR(10)
#DEFINE DCRLF CRLF+CRLF

#DEFINE SMTP_PORT  25

#DEFINE SMTP_HELP_MESSAGE    214
#DEFINE SMTP_SERVICE_READY   220
#DEFINE SMTP_SERVICE_CLOSING 221
#DEFINE SMTP_MAILACTION_OK   250
#DEFINE SMTP_START_DATA      354
#DEFINE SMTP_MAILBOX_INVALID 550

#DEFINE CONTENT_TYPE_MULTIPART_MIXED "multipart/mixed"
#DEFINE CONTENT_TYPE_TEXT_PLAIN      "text/plain"
#DEFINE CONTENT_TYPE_TEXT_HTML       "text/html"
#DEFINE CONTENT_TYPE_OCTET_STREAM    "application/octet-stream"

#DEFINE BASE64_LINE_LENGTH 76

